logging:
  level:
    root: ERROR
    org.apache: ERROR
    org.springframework.web: ERROR
    org.springframework.boot.StartupInfoLogger: INFO
    org.springframework.boot.SpringApplication: INFO
    org.springframework.context.support.DefaultLifecycleProcessor: INFO
    org.apache.geode.internal.cache.PoolFactoryImpl: OFF
    org.springframework.boot.tomcat: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  metrics:
    enable:
      jdbc: true
server:
  port: 0

spring:
  data:
    gemfire:
      cache:
        log-level: error
      pool:
        locators: localhost[10334]
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  threads:
    virtual:
      enabled: true